personality = "pragmatic"
model = "gpt-5.5"
model_reasoning_effort = "medium"

[features]
multi_agent = true

[mcp_servers.FigmaMCPDesign]
command = "/home/sonnn/Work/cursor-talk-to-figma-mcp/figma-mcp-design/bin/linux-amd64/figma-mcp-design"
args = []

[mcp_servers.FigmaMCPDesign.tools.get_document_info]
approval_mode = "approve"

[mcp_servers.FigmaMCPDesign.tools.get_node_info]
approval_mode = "approve"

[mcp_servers.FigmaMCPDesign.tools.resize_node]
approval_mode = "approve"

[mcp_servers.FigmaMCPDesign.tools.set_focus]
approval_mode = "approve"
